language: node_js
node_js: node
deploy:
  provider: heroku
  app: sleepy-scrubland-19366
  on:
    repo: sulfurshade/blog-app-mongoose-challenge-solution
  api_key:
    secure: mjG5i5dwtqViaIYUjHFVSGXj5m4/bPJ1WcaEVsMwkIar8yleoR+MiFjoJ4Ja1oKPgKQU0yTgu105mOcSVUTnsYBFRkRcEgalWzMkgAE7y3XL67BMHfLGUzcKFUHS40JD0T8uImv7f596K4T2OmEU4jIwOqR4bOjqYyh/fkDOdxS3dTlopZ4zxv8CsCi2zeNJKgwLW5YIv0G9A+N05PbLi02hYMOD19nkDL+HQYdUlA6SbsnE+mYm8GBdXwFNzS0ShMBOXJcGXwJlDdYvyidTtZmAB7i3EB1yGDUzXdS+zoe0dpMf5v6z3Wm78AT0sayXcbZH1E6Khecp7akxoDG7cXdtqdX9WK3WF+Mb5By8dgy6VrB1/Navol9HaoURy7KKKotOMZFeWOesHr0SdLW6NJuThLyUBSxLvbc5tMPMLFZ704eL8m4A73ikW90BOzzHPAXqL6KlueWlgoC0VAlGceR1LMdAa81ON2JBQoRQInVGs3H5NrRK2C9BpXd3wvxsxzwpcay+YUhwTlCuz8ozy/F9g+reukdJ7G1Se1geNZe6sOtbC7t5lea6GvIqjqgqyd55vbnmqMkIOvqfGfWzdnbWKIj9ozxH/iGksjJZpWxLktmkcC3Qa6g5kkICZANk5AbafJmPwqqEqUOI7raY3zcUmdj5sYpsErytgrmRI6I=
